In [1]:
import numpy as np
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv('real_estate_data.csv').drop(22)

In [3]:
df.shape

(246, 7)

In [4]:
df.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."

In [5]:
df[["PropertyName","TopFacilities"]][0:10]

,PropertyName,TopFacilities
0,Smartworld One DXP,"['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."
5,Whiteland The Aspen,"['Reflexology Park', 'Card Room', 'High Speed ..."
6,Bestech Altura,"['Swimming Pool', 'Football', 'Flower Garden',..."
7,Elan The Presidential,"['Swimming Pool', 'Aerobics Centre', 'Shopping..."
8,Signature Global City 92,"['Swimming Pool', 'Reflexology Park', 'Terrace..."
9,Emaar Digihomes,"['Mini Theatre', 'Swimming Pool', 'Salon', 'Ca..."

In [6]:

import re


def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [7]:
df.head(1)

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete..."

In [8]:
df['Facilities']=df['TopFacilities'].apply(' '.join)

In [9]:

tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [10]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['Facilities'])

In [11]:
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.14379378,
        0.14379378],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(246, 953))

In [12]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [13]:
cosine_sim1.shape

(246, 246)

In [14]:
def rec_prop(property_name , cosine_sim = cosine_sim1):
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]
    sim_score = list(enumerate(cosine_sim[idx]))
    sim_score = sorted(sim_score, key=lambda x: x[1], reverse=True)
    sim_score = sim_score[1:6]
    pidx = [i[0] for i in sim_score]
    recomendation_df =  pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[pidx].values,
        'similarity_score': [i[1] for i in sim_score]
    })
    return recomendation_df

In [15]:
idx = df.index[df['PropertyName'] == 'M3M Crown'].tolist()[0]

In [16]:
rec_prop('M3M Crown')

                              PropertyName  similarity_score
0                           DLF The Ultima          0.358603
1                            BPTP Pedestal          0.331763
2                      Ireo Victory Valley          0.318586
3                            M3M Sky Lofts          0.309176
4  Central Park Flower Valley Mikasa Plots          0.297431

In [17]:
sim_score = list(enumerate(cosine_sim1[idx]))

In [18]:
sim_score

[(0, np.float64(0.010951589538864515)),
 (1, np.float64(1.0000000000000002)),
 (2, np.float64(0.019821211060493036)),
 (3, np.float64(0.1296332817539559)),
 (4, np.float64(0.15888474057768504)),
 (5, np.float64(0.019310272324387357)),
 (6, np.float64(0.21700920287542233)),
 (7, np.float64(0.0084010073622641)),
 (8, np.float64(0.041269095672560804)),
 (9, np.float64(0.07992243485499474)),
 (10, np.float64(0.013031464375486135)),
 (11, np.float64(0.03223439184656369)),
 (12, np.float64(0.14896009351131334)),
 (13, np.float64(0.11517012009261494)),
 (14, np.float64(0.029979471390467638)),
 (15, np.float64(0.011399439203418632)),
 (16, np.float64(0.0)),
 (17, np.float64(0.01918649830583175)),
 (18, np.float64(0.06587679948437511)),
 (19, np.float64(0.03734590222631334)),
 (20, np.float64(0.21621658180837194)),
 (21, np.float64(0.0452474461444466)),
 (22, np.float64(0.05640567615225693)),
 (23, np.float64(0.15373791911523915)),
 (24, np.float64(0.09988347503176563)),
 (25, np.float64(0.17319521378156588)),
 (26, np.float64(0.013364895799443739)),
 (27, np.float64(0.14997326931905233)),
 (28, np.float64(0.07054216595536518)),
 (29, np.float64(0.028411200859184856)),
 (30, np.float64(0.04932733101894407)),
 (31, np.float64(0.009068996678867765)),
 (32, np.float64(0.01626611250733705)),
 (33, np.float64(0.08873273106301188)),
 (34, np.float64(0.010623266108723127)),
 (35, np.float64(0.1904348188973809)),
 (36, np.float64(0.010033412099714197)),
 (37, np.float64(0.018960186247158027)),
 (38, np.float64(0.078640961445063)),
 (39, np.float64(0.018044962361908345)),
 (40, np.float64(0.28166250341736515)),
 (41, np.float64(0.02775969980296817)),
 (42, np.float64(0.0464805565223288)),
 (43, np.float64(0.028411716999977833)),
 (44, np.float64(0.009449782900299679)),
 (45, np.float64(0.00866776361833795)),
 (46, np.float64(0.03118121489428584)),
 (47, np.float64(0.11623455420998147)),
 (48, np.float64(0.06834503235774768)),
 (49, np.float64(0.03922142268375753)),
 (50, np.float64(0.0)),
 (51, np.float64(0.09422017323249188)),
 (52, np.float64(0.1050681163835472)),
 (53, np.float64(0.021773359300177233)),
 (54, np.float64(0.05210819757703665)),
 (55, np.float64(0.20724173952279726)),
 (56, np.float64(0.10536550408454488)),
 (57, np.float64(0.0330436154969921)),
 (58, np.float64(0.03003709963535235)),
 (59, np.float64(0.0913175235275688)),
 (60, np.float64(0.11005318143880967)),
 (61, np.float64(0.04074264023197411)),
 (62, np.float64(0.019720918601510703)),
 (63, np.float64(0.03395979534168212)),
 (64, np.float64(0.0)),
 (65, np.float64(0.020318073446138316)),
 (66, np.float64(0.009940320904326637)),
 (67, np.float64(0.29741233419695945)),
 (68, np.float64(0.0)),
 (69, np.float64(0.014113670915728023)),
 (70, np.float64(0.031771769090412294)),
 (71, np.float64(0.1398717942223478)),
 (72, np.float64(0.03512407211296284)),
 (73, np.float64(0.027283906414091376)),
 (74, np.float64(0.31858623396699676)),
 (75, np.float64(0.04584364609693828)),
 (76, np.float64(0.03430298217914296)),
 (77, np.float64(0.0875449098513372)),
 (78, np.float64(0.15179406066220785)),
 (79, np.float64(0.0753744830018688)),
 (80, np.float64(0.1630169192524145)),
 (81, np.float64(0.019174270016890798)),
 (82, np.float64(0.24264785543805473)),
 (83, np.float64(0.027994229063698355)),
 (84, np.float64(0.010518156314630552)),
 (85, np.float64(0.35860320390686057)),
 (86, np.float64(0.054349401975600724)),
 (87, np.float64(0.0727555085477666)),
 (88, np.float64(0.1508134390463069)),
 (89, np.float64(0.29743060271126887)),
 (90, np.float64(0.1294176318856959)),
 (91, np.float64(0.15279624584655668)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0640173282597493)),
 (94, np.float64(0.023326540833591407)),
 (95, np.float64(0.15804923284672465)),
 (96, np.float64(0.010636553635916292)),
 (97, np.float64(0.04596752939415119)),
 (98, np.float64(0.13804248157255858)),
 (99, np.float64(0.08363021422441959)),
 (100, np.float64(0.0)),
 (101, np.float64(0.06444364886885179)),
 (102, np.float64(0.09646962036879626)),
 (103, np.float64(0.009583308742501032)),
 (104, np.float64(0.01044194666252669)),
 (105, np.float64(0.15912758579528435)),
 (106, np.float64(0.01025489631484822)),
 (107, np.float64(0.010569823041302159)),
 (108, np.float64(0.019033960650041135)),
 (109, np.float64(0.009098963716524442)),
 (110, np.float64(0.10953436770498619)),
 (111, np.float64(0.11876809483184869)),
 (112, np.float64(0.08639599769419008)),
 (113, np.float64(0.0424315409798448)),
 (114, np.float64(0.010412256671563761)),
 (115, np.float64(0.009687098753795465)),
 (116, np.float64(0.06848921595786003)),
 (117, np.float64(0.21754728989138755)),
 (118, np.float64(0.10894926858630083)),
 (119, np.float64(0.01050968493859141)),
 (120, np.float64(0.07430322889725854)),
 (121, np.float64(0.029218541647194833)),
 (122, np.float64(0.18545274846684243)),
 (123, np.float64(0.033397518090683184)),
 (124, np.float64(0.019763582946888944)),
 (125, np.float64(0.09983727467268827)),
 (126, np.float64(0.042167091442011105)),
 (127, np.float64(0.19584217615242325)),
 (128, np.float64(0.03587470893539364)),
 (129, np.float64(0.008418554312311016)),
 (130, np.float64(0.01041633420535597)),
 (131, np.float64(0.10139625510309028)),
 (132, np.float64(0.06329553197386724)),
 (133, np.float64(0.078577511631001)),
 (134, np.float64(0.018592399487769664)),
 (135, np.float64(0.010966054567970597)),
 (136, np.float64(0.008802051382238179)),
 (137, np.float64(0.0122992352608975)),
 (138, np.float64(0.00913155988935812)),
 (139, np.float64(0.10258626310924214)),
 (140, np.float64(0.03954676981043091)),
 (141, np.float64(0.009209959141286243)),
 (142, np.float64(0.05384303699955295)),
 (143, np.float64(0.06798856338955878)),
 (144, np.float64(0.028241258779366167)),
 (145, np.float64(0.3091761490494428)),
 (146, np.float64(0.009796668594099098)),
 (147, np.float64(0.0)),
 (148, np.float64(0.013596714002387338)),
 (149, np.float64(0.009582213012801887)),
 (150, np.float64(0.08383924038883303)),
 (151, np.float64(0.12278977233290123)),
 (152, np.float64(0.0)),
 (153, np.float64(0.027260474724731656)),
 (154, np.float64(0.0197949312892177)),
 (155, np.float64(0.0)),
 (156, np.float64(0.019247510591589044)),
 (157, np.float64(0.019245495545180267)),
 (158, np.float64(0.03130481802318756)),
 (159, np.float64(0.13155785794715968)),
 (160, np.float64(0.028627665634777567)),
 (161, np.float64(0.008980670787930474)),
 (162, np.float64(0.0)),
 (163, np.float64(0.09641698028787503)),
 (164, np.float64(0.14579978851231853)),
 (165, np.float64(0.029370771088856218)),
 (166, np.float64(0.10161501321629118)),
 (167, np.float64(0.07075272645394175)),
 (168, np.float64(0.025779025385975735)),
 (169, np.float64(0.09423247179791056)),
 (170, np.float64(0.04983697487576027)),
 (171, np.float64(0.0787809262708687)),
 (172, np.float64(0.06602267006518968)),
 (173, np.float64(0.012979390824657197)),
 (174, np.float64(0.0)),
 (175, np.float64(0.018400104421937583)),
 (176, np.float64(0.051651352797270025)),
 (177, np.float64(0.05738613083543727)),
 (178, np.float64(0.009084122198441756)),
 (179, np.float64(0.05660759725576666)),
 (180, np.float64(0.0)),
 (181, np.float64(0.00956106465653578)),
 (182, np.float64(0.05046338515057435)),
 (183, np.float64(0.15716165955917108)),
 (184, np.float64(0.008681262256636216)),
 (185, np.float64(0.0)),
 (186, np.float64(0.04832217217900213)),
 (187, np.float64(0.0815865991863307)),
 (188, np.float64(0.04237256102295356)),
 (189, np.float64(0.09505792922601146)),
 (190, np.float64(0.0)),
 (191, np.float64(0.0)),
 (192, np.float64(0.04485873168281782)),
 (193, np.float64(0.019449033811756982)),
 (194, np.float64(0.03174885380201785)),
 (195, np.float64(0.03697399228426681)),
 (196, np.float64(0.08048540435847237)),
 (197, np.float64(0.21749050906849515)),
 (198, np.float64(0.021521142337998594)),
 (199, np.float64(0.03362758886301827)),
 (200, np.float64(0.012691961462803311)),
 (201, np.float64(0.1655503472461066)),
 (202, np.float64(0.18140142177520333)),
 (203, np.float64(0.0)),
 (204, np.float64(0.021162401391297138)),
 (205, np.float64(0.032188022781503574)),
 (206, np.float64(0.06995446189282392)),
 (207, np.float64(0.02640987282813499)),
 (208, np.float64(0.019181139690258177)),
 (209, np.float64(0.0088449683350144)),
 (210, np.float64(0.008885750812428345)),
 (211, np.float64(0.11541375866884922)),
 (212, np.float64(0.02422595678056828)),
 (213, np.float64(0.02107183928581646)),
 (214, np.float64(0.09123810983222408)),
 (215, np.float64(0.09417431523866607)),
 (216, np.float64(0.0)),
 (217, np.float64(0.07102423797650005)),
 (218, np.float64(0.0)),
 (219, np.float64(0.08280452287595554)),
 (220, np.float64(0.013250222459986053)),
 (221, np.float64(0.02957000135804793)),
 (222, np.float64(0.018558581665133776)),
 (223, np.float64(0.009905309008957332)),
 (224, np.float64(0.009119488821108213)),
 (225, np.float64(0.03368392549497827)),
 (226, np.float64(0.33176299517252417)),
 (227, np.float64(0.009005966104650695)),
 (228, np.float64(0.0)),
 (229, np.float64(0.00861441113091231)),
 (230, np.float64(0.01866751583633471)),
 (231, np.float64(0.15324279593886486)),
 (232, np.float64(0.02806468171211142)),
 (233, np.float64(0.017564413732043045)),
 (234, np.float64(0.011801587613879453)),
 (235, np.float64(0.026511305536141245)),
 (236, np.float64(0.009992229223652711)),
 (237, np.float64(0.02945546848429091)),
 (238, np.float64(0.028471478195919737)),
 (239, np.float64(0.08764707415876236)),
 (240, np.float64(0.018410884243102436)),
 (241, np.float64(0.009709839194258765)),
 (242, np.float64(0.022333759115293866)),
 (243, np.float64(0.11904240802210878)),
 (244, np.float64(0.015555341116931522)),
 (245, np.float64(0.00963851629954565))]

In [19]:
sim_score = sorted(sim_score, key=lambda x: x[1], reverse=True)

In [20]:
sim_score =sim_score[1:6]

In [21]:
pidx = [i[0] for i in sim_score]
pidx

[85, 226, 74, 145, 89]

In [22]:
pd.DataFrame({
    'PropertyName': df['PropertyName'].iloc[pidx],
    'similarity_score': sim_score
})

                                PropertyName            similarity_score
86                            DLF The Ultima   (85, 0.35860320390686057)
227                            BPTP Pedestal  (226, 0.33176299517252417)
75                       Ireo Victory Valley   (74, 0.31858623396699676)
146                            M3M Sky Lofts   (145, 0.3091761490494428)
90   Central Park Flower Valley Mikasa Plots   (89, 0.29743060271126887)

In [23]:
df.head(1)

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities,Facilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","[Swimming Pool, Salon, Restaurant, Spa, Cafete...",Swimming Pool Salon Restaurant Spa Cafeteria S...

In [24]:
df[['PropertyName', 'PriceDetails']]['PriceDetails'][0]

"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}"

In [25]:
import ast
import re
import numpy as np

# area parser

In [26]:
def parse_area(area):

    nums = re.findall(r"\d+(?:,\d+)?(?:\.\d+)?", str(area))

    nums = [float(x.replace(",", "")) for x in nums]

    if len(nums)==1:
        return nums[0], nums[0]

    elif len(nums)>=2:
        return min(nums), max(nums)

    return np.nan, np.nan

# price parser

In [27]:
def parse_price(price):

    nums = re.findall(r"\d+(?:\.\d+)?", str(price))

    vals=[]

    for n in nums:

        vals.append(float(n))

    if "L" in price:

        vals=[x/100 for x in vals]

    if len(vals)==1:

        return vals[0],vals[0]

    elif len(vals)>=2:

        return min(vals),max(vals)

    return np.nan,np.nan

In [28]:
def extract_features(detail):

    try:
        detail = ast.literal_eval(detail)
    except:
        return {}

    output={}

    for bhk,info in detail.items():

        output[f"{bhk}_building_type"]=info.get("building_type")

        low,high=parse_area(info.get("area"))

        output[f"{bhk}_area_low"]=low
        output[f"{bhk}_area_high"]=high

        low,high=parse_price(info.get("price-range"))

        output[f"{bhk}_price_low"]=low
        output[f"{bhk}_price_high"]=high
        output[f"{bhk}_area_type"] = info.get("area_type")

    return output

In [29]:
feature_df = df["PriceDetails"].apply(extract_features)

feature_df = pd.json_normalize(feature_df)

df_final = pd.concat(
    [
        df['PropertyName'],
        feature_df
    ],
    axis=1
)

In [30]:
df_final.set_index("PropertyName",inplace=True)

In [31]:
df_final.iloc[0]

2 BHK_building_type      Apartment
2 BHK_area_low              1370.0
2 BHK_area_high             1370.0
2 BHK_price_low                2.0
2 BHK_price_high               2.4
2 BHK_area_type        Carpet Area
3 BHK_building_type      Apartment
3 BHK_area_low              1850.0
3 BHK_area_high             2050.0
3 BHK_price_low               2.25
3 BHK_price_high              3.59
3 BHK_area_type        Carpet Area
4 BHK_building_type      Apartment
4 BHK_area_low              2600.0
4 BHK_area_high             2600.0
4 BHK_price_low               3.24
4 BHK_price_high              4.56
4 BHK_area_type        Carpet Area
Land_building_type             NaN
Land_area_low                  NaN
Land_area_high                 NaN
Land_price_low                 NaN
Land_price_high                NaN
Land_area_type                 NaN
5 BHK_building_type            NaN
5 BHK_area_low                 NaN
5 BHK_area_high                NaN
5 BHK_price_low                NaN
5 BHK_price_high               NaN
5 BHK_area_type                NaN
1 BHK_building_type            NaN
1 BHK_area_low                 NaN
1 BHK_area_high                NaN
1 BHK_price_low                NaN
1 BHK_price_high               NaN
1 BHK_area_type                NaN
1 RK_building_type             NaN
1 RK_area_low                  NaN
1 RK_area_high                 NaN
1 RK_price_low                 NaN
1 RK_price_high                NaN
1 RK_area_type                 NaN
6 BHK_building_type            NaN
6 BHK_area_low                 NaN
6 BHK_area_high                NaN
6 BHK_price_low                NaN
6 BHK_price_high               NaN
6 BHK_area_type                NaN
Name: Smartworld One DXP, dtype: object

In [32]:
cat_col = df_final.select_dtypes(include='object').columns.tolist()

C:\Users\HP\AppData\Local\Temp\ipykernel_25848\2276582199.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = df_final.select_dtypes(include='object').columns.tolist()

In [33]:
cat_col

['2 BHK_building_type',
 '2 BHK_area_type',
 '3 BHK_building_type',
 '3 BHK_area_type',
 '4 BHK_building_type',
 '4 BHK_area_type',
 'Land_building_type',
 'Land_area_type',
 '5 BHK_building_type',
 '5 BHK_area_type',
 '1 BHK_building_type',
 '1 BHK_area_type',
 '1 RK_building_type',
 '1 RK_area_type',
 '6 BHK_building_type',
 '6 BHK_area_type']

In [34]:
ohe_df = pd.get_dummies(df_final,columns=cat_col, drop_first=True, dtype="uint8")

In [35]:
ohe_df.fillna(0,inplace=True)

,2 BHK_area_low,2 BHK_area_high,2 BHK_price_low,2 BHK_price_high,3 BHK_area_low,3 BHK_area_high,3 BHK_price_low,3 BHK_price_high,4 BHK_area_low,4 BHK_area_high,...,4 BHK_area_type_Super Built-up Area,5 BHK_building_type_Independent Floor,5 BHK_building_type_Villa,5 BHK_area_type_Carpet Area,5 BHK_area_type_Super Built-up Area,1 BHK_building_type_Service Apartment,1 BHK_area_type_Super Built-up Area,1 RK_area_type_Super Built-up Area,6 BHK_building_type_Villa,6 BHK_area_type_Super Built-up Area
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,1370.0,1370.0,2.0000,2.4000,1850.0,2050.0,2.25,3.59,2600.0,2600.0,...,0,0,0,0,0,0,0,0,0,0
M3M Crown,0.0,0.0,0.0000,0.0000,1605.0,2170.0,2.20,3.03,2248.0,2670.0,...,1,0,0,0,0,0,0,0,0,0
Adani Brahma Samsara Vilasa,0.0,0.0,0.0000,0.0000,1800.0,3150.0,2.43,15.75,2750.0,4500.0,...,1,0,0,0,0,0,0,0,0,0
Sobha City,1381.0,1692.0,1.5500,3.2100,1711.0,2343.0,1.76,4.79,2423.0,2963.0,...,1,0,0,0,0,0,0,0,0,0
Signature Global City 93,981.0,1118.0,0.0106,0.9301,1235.0,1530.0,1.12,1.45,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,964.0,964.0,1.3500,1.3500,1127.0,1127.0,1.55,1.55,1562.0,1562.0,...,1,0,0,0,0,0,0,0,0,0
Pyramid Urban Homes 2,500.0,625.0,0.0000,0.0000,0.0,0.0,0.00,0.00,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
Satya The Hermitage,1450.0,1450.0,0.8000,0.8000,1991.0,1991.0,1.00,1.00,2639.0,4711.0,...,1,0,0,0,1,0,0,0,0,0
BPTP Spacio,1000.0,1079.0,0.0000,0.0000,1225.0,1865.0,0.00,0.00,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
SS The Coralwood,1320.0,1425.0,0.0000,0.0000,1750.0,1890.0,1.10,1.19,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

norm_ohe_df = pd.DataFrame(scaler.fit_transform(ohe_df),columns=ohe_df.columns,index=ohe_df.index)

In [37]:
norm_ohe_df

,2 BHK_area_low,2 BHK_area_high,2 BHK_price_low,2 BHK_price_high,3 BHK_area_low,3 BHK_area_high,3 BHK_price_low,3 BHK_price_high,4 BHK_area_low,4 BHK_area_high,...,4 BHK_area_type_Super Built-up Area,5 BHK_building_type_Independent Floor,5 BHK_building_type_Villa,5 BHK_area_type_Carpet Area,5 BHK_area_type_Super Built-up Area,1 BHK_building_type_Service Apartment,1 BHK_area_type_Super Built-up Area,1 RK_area_type_Super Built-up Area,6 BHK_building_type_Villa,6 BHK_area_type_Super Built-up Area
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,1.223499,1.020101,1.229266,1.063789,0.553787,0.370864,0.490560,0.414174,0.602838,0.212073,...,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
M3M Crown,-0.893541,-0.896660,-0.418097,-0.446627,0.293086,0.472749,0.462219,0.245937,0.382746,0.243172,...,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Adani Brahma Samsara Vilasa,-0.893541,-0.896660,-0.418097,-0.446627,0.500583,1.304803,0.592590,4.067311,0.696627,1.056178,...,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Sobha City,1.240497,1.470610,0.858610,1.573554,0.405879,0.619632,0.212813,0.774681,0.492166,0.373342,...,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Signature Global City 93,0.622383,0.667529,-0.409366,0.138722,-0.100626,-0.070634,-0.149960,-0.228730,-1.022842,-0.943016,...,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,0.596113,0.452068,0.693873,0.402982,-0.215547,-0.412795,0.093778,-0.198688,-0.046184,-0.249074,...,1.178282,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Pyramid Urban Homes 2,-0.120899,-0.022226,-0.418097,-0.446627,-1.414772,-1.369658,-0.784811,-0.664343,-1.022842,-0.943016,...,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
Satya The Hermitage,1.347122,1.132029,0.240848,0.056845,0.703823,0.320771,-0.217979,-0.363920,0.627223,1.149918,...,1.178282,-0.111111,-0.216353,-0.171139,2.497057,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
BPTP Spacio,0.651744,0.612964,-0.418097,-0.446627,-0.111267,0.213793,-0.784811,-0.664343,-1.022842,-0.943016,...,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111
SS The Coralwood,1.146235,1.097051,-0.418097,-0.446627,0.447378,0.235019,-0.161296,-0.306840,-1.022842,-0.943016,...,-0.848693,-0.111111,-0.216353,-0.171139,-0.400471,-0.111111,-0.194871,-0.063888,-0.063888,-0.111111

In [38]:
cosine_sim2 = cosine_similarity(norm_ohe_df,norm_ohe_df)

In [39]:
cosine_sim2

array([[ 1.        , -0.28748044, -0.12094965, ..., -0.1195517 ,
        -0.20151881, -0.09260065],
       [-0.28748044,  1.        ,  0.13281758, ..., -0.07037406,
        -0.06747354, -0.09791125],
       [-0.12094965,  0.13281758,  1.        , ..., -0.13878337,
        -0.32277409, -0.27623977],
       ...,
       [-0.1195517 , -0.07037406, -0.13878337, ...,  1.        ,
         0.10459656,  0.18266425],
       [-0.20151881, -0.06747354, -0.32277409, ...,  0.10459656,
         1.        ,  0.94301388],
       [-0.09260065, -0.09791125, -0.27623977, ...,  0.18266425,
         0.94301388,  1.        ]], shape=(246, 246))

In [40]:
def recommend_properties_with_scores(property_name, top_n=5):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim2[norm_ohe_df.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = norm_ohe_df.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('M3M Golf Hills')

              PropertyName  SimilarityScore
0               BPTP Terra         0.968899
1  AIPL The Peaceful Homes         0.968865
2           Unitech Escape         0.968816
3        DLF Regal Gardens         0.950464
4               Sobha City         0.948994

# 3 recommendation sys

In [41]:
def parse_location(x):

    if pd.isna(x):
        return {}

    if isinstance(x, dict):
        return x

    try:
        return ast.literal_eval(x)
    except:
        return {}

In [42]:
def distance_to_km(distance):

    if pd.isna(distance):
        return np.nan

    distance = str(distance).strip().lower()

    num = re.findall(r"\d+\.?\d*", distance)

    if len(num)==0:
        return np.nan

    num = float(num[0])

    if "m" in distance and "km" not in distance:
        return num/1000

    return num

In [43]:
def normalize_location_name(name):

    name = name.lower().strip()

    replacements = {

        "nh48":"nh-48",
        "nh 48":"nh-48",
        "nh-48":"nh-48",

        "igi airport":"airport",
        "indira gandhi international airport":"airport",
        "airport":"airport",

        "rapid metro":"metro",
        "metro station":"metro",
        "metro":"metro",

        "railway station":"railway station",

        "hospital":"hospital",

        "school":"school"

    }

    return replacements.get(name, name)

In [44]:
rows = []

for loc in df["LocationAdvantages"]:

    loc = parse_location(loc)

    temp = {}

    for place, dist in loc.items():

        place = normalize_location_name(place)

        temp[place] = distance_to_km(dist)

    rows.append(temp)

location_df = pd.DataFrame(rows, index=df["PropertyName"])

In [45]:
location_df1 = location_df.fillna(location_df.max().max() + 5)

In [46]:
location_df1

,bajghera road,palam vihar halt,dpsg palam vihar,park hospital,gurgaon railway station,the northcap university,dwarka expy,hyatt place gurgaon udyog vihar,"dwarka sector 21, metro station",pacific d21 mall,...,mcc cricket ground dhankot,the shri ram school aravali,taj city centre gurugram,minda industries corporate office,"rampura flyover, naurangpur rd",manesar toll plaza - kherki daula,"imt manesar, gurugram",holiday inn,sector 84 road,skyview corporate park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0.8,2.5,3.1,3.1,4.9,5.4,1.2,7.7,7.2,7.4,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
M3M Crown,59.5,59.5,59.5,59.5,59.5,4.4,59.5,59.5,59.5,8.2,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
Adani Brahma Samsara Vilasa,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
Sobha City,59.5,59.5,59.5,59.5,59.5,9.2,59.5,59.5,59.5,59.5,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
Signature Global City 93,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,...,59.5,3.9,4.0,59.5,59.5,59.5,59.5,59.5,59.5,59.5
Pyramid Urban Homes 2,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,...,59.5,59.5,59.5,3.1,3.7,6.1,7.7,3.0,59.5,59.5
Satya The Hermitage,59.5,59.5,59.5,59.5,3.3,8.8,59.5,59.5,59.5,59.5,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
BPTP Spacio,59.5,59.5,59.5,59.5,7.0,59.5,59.5,59.5,59.5,59.5,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5
SS The Coralwood,59.5,59.5,59.5,59.5,59.5,59.5,2.0,59.5,59.5,59.5,...,59.5,59.5,59.5,59.5,59.5,59.5,59.5,59.5,0.6,12.4

In [54]:
import pickle
with open("location_df.pkl",'wb') as f:
    pickle.dump(location_df1,f)

In [47]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

location_scaled = pd.DataFrame(scaler.fit_transform(location_df1),columns=location_df1.columns,index=location_df1.index)

In [48]:

location_scaled

,bajghera road,palam vihar halt,dpsg palam vihar,park hospital,gurgaon railway station,the northcap university,dwarka expy,hyatt place gurgaon udyog vihar,"dwarka sector 21, metro station",pacific d21 mall,...,mcc cricket ground dhankot,the shri ram school aravali,taj city centre gurugram,minda industries corporate office,"rampura flyover, naurangpur rd",manesar toll plaza - kherki daula,"imt manesar, gurugram",holiday inn,sector 84 road,skyview corporate park
PropertyName,,,,,,,,,,,,,,,,,,,,,
Smartworld One DXP,0.004241,0.0,0.0,0.039182,0.056995,0.049209,0.020003,0.119796,0.0,0.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
M3M Crown,1.000000,1.0,1.0,1.000000,1.000000,0.031634,1.000000,1.000000,1.0,0.015355,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Adani Brahma Samsara Vilasa,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Sobha City,1.000000,1.0,1.0,1.000000,1.000000,0.115993,1.000000,1.000000,1.0,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Signature Global City 93,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DLF Princeton Estate,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,...,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Pyramid Urban Homes 2,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
Satya The Hermitage,1.000000,1.0,1.0,1.000000,0.029361,0.108963,1.000000,1.000000,1.0,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
BPTP Spacio,1.000000,1.0,1.0,1.000000,0.093264,1.000000,1.000000,1.000000,1.0,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
SS The Coralwood,1.000000,1.0,1.0,1.000000,1.000000,1.000000,0.033451,1.000000,1.0,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0

In [49]:
cosine_sim3 = cosine_similarity(location_scaled)

In [50]:
cosine_sim3.shape

(246, 246)

In [61]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 30*cosine_sim1 + 20*cosine_sim2 + 8*cosine_sim3
    # cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df1.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df1.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('Ireo Victory Valley')

               PropertyName  SimilarityScore
0             DLF The Crest        35.481459
1    Pioneer Urban Presidia        35.353374
2        Ambience Creacions        34.663120
3               SS The Leaf        31.661376
4    Silverglades The Melia        31.290804
..                      ...              ...
240          JMS The Nation        -6.107699
241       Vatika Aspiration        -6.164759
242          JMS Prime Land        -6.342487
243           Corona Greens        -6.368617
244              Yash Vihar        -6.479298

[245 rows x 2 columns]

In [190]:
(3*cosine_sim3 + 5*cosine_sim2 + 6*cosine_sim1).shape

(246, 246)

In [58]:
with open("cosine_sim1.pkl",'wb') as f:
    pickle.dump(cosine_sim1,f)

In [59]:
with open("cosine_sim2.pkl",'wb') as f:
    pickle.dump(cosine_sim2,f)

In [60]:
with open("cosine_sim3.pkl",'wb') as f:
    pickle.dump(cosine_sim3,f)